# Generated by Django 4.0.4 on 2022-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=8, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=60, verbose_name='Endereço')),
                ('status_pendencia', models.BooleanField(default=False)),
                ('status_ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
