# Generated by Django 4.0.4 on 2022-04-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Autor')),
                ('status_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('nome_livro', models.CharField(max_length=40, verbose_name='Nome do Livro')),
                ('ano_publicacao', models.DateField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('status_ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.autor')),
            ],
        ),
    ]
