# Generated by Django 4.0.4 on 2022-04-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(auto_now_add=True, verbose_name='Data de emprestimo')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data limite de devolução')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de devolução')),
                ('status_emprestimo', models.BooleanField(choices=[('PEN.', 'Pendente'), ('QUI.', 'Quitado')], default='PEN.', verbose_name='Status do emprestimo')),
                ('status_ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.aluno')),
                ('livros', models.ManyToManyField(related_name='emprestimos', to='livros.livro')),
            ],
        ),
    ]
